// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo/grpc/user_service.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProfileCreateRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileCreateRequest) Reset()         { *m = ProfileCreateRequest{} }
func (m *ProfileCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileCreateRequest) ProtoMessage()    {}
func (*ProfileCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_service_2218d4fca70c9ce6, []int{0}
}
func (m *ProfileCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileCreateRequest.Unmarshal(m, b)
}
func (m *ProfileCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileCreateRequest.Marshal(b, m, deterministic)
}
func (dst *ProfileCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileCreateRequest.Merge(dst, src)
}
func (m *ProfileCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileCreateRequest.Size(m)
}
func (m *ProfileCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileCreateRequest proto.InternalMessageInfo

func (m *ProfileCreateRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ProfileCreateRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type ProfileCreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileCreateResponse) Reset()         { *m = ProfileCreateResponse{} }
func (m *ProfileCreateResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileCreateResponse) ProtoMessage()    {}
func (*ProfileCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_service_2218d4fca70c9ce6, []int{1}
}
func (m *ProfileCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileCreateResponse.Unmarshal(m, b)
}
func (m *ProfileCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileCreateResponse.Marshal(b, m, deterministic)
}
func (dst *ProfileCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileCreateResponse.Merge(dst, src)
}
func (m *ProfileCreateResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileCreateResponse.Size(m)
}
func (m *ProfileCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileCreateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProfileCreateRequest)(nil), "user.ProfileCreateRequest")
	proto.RegisterType((*ProfileCreateResponse)(nil), "user.ProfileCreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	ProfileCreate(ctx context.Context, in *ProfileCreateRequest, opts ...grpc.CallOption) (*ProfileCreateResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ProfileCreate(ctx context.Context, in *ProfileCreateRequest, opts ...grpc.CallOption) (*ProfileCreateResponse, error) {
	out := new(ProfileCreateResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/ProfileCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	ProfileCreate(context.Context, *ProfileCreateRequest) (*ProfileCreateResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ProfileCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ProfileCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ProfileCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ProfileCreate(ctx, req.(*ProfileCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProfileCreate",
			Handler:    _UserService_ProfileCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo/grpc/user_service.proto",
}

func init() {
	proto.RegisterFile("demo/grpc/user_service.proto", fileDescriptor_user_service_2218d4fca70c9ce6)
}

var fileDescriptor_user_service_2218d4fca70c9ce6 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x2c, 0x62, 0x56, 0x84, 0xb2, 0x58, 0x94, 0xb4, 0x07, 0xc9, 0x41, 0x8a, 0xd0,
	0x2c, 0xea, 0x4d, 0x6f, 0x7a, 0x17, 0xa9, 0x78, 0x2e, 0xdb, 0x74, 0xb2, 0x5d, 0xd8, 0xec, 0xc4,
	0xdd, 0x49, 0xc0, 0xab, 0xaf, 0xe0, 0xdb, 0x78, 0xf2, 0x1d, 0x7c, 0x05, 0x2f, 0xbe, 0x85, 0x6c,
	0x82, 0x07, 0xdb, 0xde, 0x96, 0xff, 0xff, 0x76, 0x66, 0xfe, 0x9f, 0x4d, 0x56, 0x50, 0xa1, 0x50,
	0xae, 0x2e, 0x44, 0xe3, 0xc1, 0x2d, 0x3c, 0xb8, 0x56, 0x17, 0x90, 0xd7, 0x0e, 0x09, 0xf9, 0x20,
	0x68, 0xe9, 0x44, 0x21, 0x2a, 0x03, 0x42, 0xd6, 0x5a, 0x48, 0x6b, 0x91, 0x24, 0x69, 0xb4, 0xbe,
	0x67, 0xd2, 0x5b, 0xa5, 0x69, 0xdd, 0x2c, 0xf3, 0x02, 0x2b, 0x61, 0x5e, 0x4b, 0x12, 0x9d, 0x5c,
	0xcc, 0x14, 0xd8, 0x59, 0x2b, 0x8d, 0x5e, 0x49, 0x02, 0xb1, 0xf5, 0xe8, 0x3f, 0x67, 0x6b, 0x76,
	0xfc, 0xe8, 0xb0, 0xd4, 0x06, 0xee, 0x1d, 0x48, 0x82, 0x39, 0xbc, 0x34, 0xe0, 0x89, 0x4f, 0x19,
	0x2b, 0xb5, 0xf3, 0xb4, 0xb0, 0xb2, 0x82, 0xd3, 0xe8, 0x2c, 0x9a, 0x26, 0x77, 0xc9, 0xc7, 0xcf,
	0xe7, 0xde, 0xc0, 0xc5, 0xc3, 0x68, 0x9e, 0x74, 0xe6, 0x83, 0xac, 0x80, 0x9f, 0xb3, 0xc4, 0xc8,
	0x3f, 0x30, 0xde, 0x04, 0x0f, 0x82, 0x17, 0xb8, 0xec, 0x84, 0x8d, 0x36, 0x36, 0xf9, 0x1a, 0xad,
	0x87, 0x2b, 0x62, 0x87, 0xcf, 0x1e, 0xdc, 0x53, 0x1f, 0x9c, 0x03, 0x3b, 0xfa, 0xc7, 0xf1, 0x34,
	0x0f, 0x25, 0xe4, 0xbb, 0xce, 0x4c, 0xc7, 0x3b, 0xbd, 0x7e, 0x70, 0x36, 0x7e, 0xfb, 0xfa, 0x7e,
	0x8f, 0x47, 0xd9, 0x50, 0xb4, 0x97, 0x5d, 0xb9, 0xa1, 0x99, 0xc0, 0xdd, 0x44, 0x17, 0xcb, 0xfd,
	0x2e, 0xff, 0xf5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x60, 0x90, 0xb6, 0xe3, 0x80, 0x01, 0x00,
	0x00,
}
